### ISSUE TITLE
Best approach to theming/overriding vars 

### ISSUE THREAD

**Issue by yumyo** [mpaupulaire4/bulma-styled-components#6]
Thank you for this great port! 
Not a real issue here but more of a SC newbie/docs question. What is the best/recommended way to theming/variable override with your implementation?
1. Extending each component
2. Defining a theme 
3. Cloning and importing Variable.js
4. ?

**Comment by mpaupulaire4** [comment]
First off i apologize for the lack of documentation. I'm still trying to tweak a few things and haven't gotten around to finishing the docs. To override variables you add theme to the overrides prop of the BulmaStyledTheme Component

**Comment by mpaupulaire4** [comment]
Like so:

```
<BulmaStyledTheme override={{
  'primary':  'blue',
  ... your other overrides here
}}>
  ... the rest of your app
</BulmaStyledTheme>

**Comment by mpaupulaire4** [comment]
The BulmaStyledTheme component goes somewhere at the root of your app

**Comment by yumyo** [comment]
Excellent! Thank you @mpaupulaire4
