### ISSUE TITLE
Columns .is-gapless does not remove margin or padding of child columns

### ISSUE THREAD

**Issue by goras** [mpaupulaire4/bulma-styled-components#8]
In the ``src/layouts/Columns.js`` the style rule .is-gapless removes the margins of child elements with the classname **.column** which is not the one used by child columns (they're generated as .Column-{hash}).

```
...
&.is-gapless {
  & > .column {
    margin: 0;
    padding: 0 !important;
  }
  ...
}
```

Not sure of how to solve this in a nice way, but I guess a quick and simple solution would be to just target all direct children of .Columns?

**Comment by mpaupulaire4** [comment]
Thanks for catching that. You can go ahead an take a look at the above PR and let me know what you think.

**Comment by goras** [comment]
Sorry for the late response! I just installed the latest version, 1.0.1 and your fix solves the issue, nice!
